trigger: none

parameters:
  - name: location
    type: string
    default: 'westus'
  - name: RESOURCE_GROUP
    type: string
    default: 'projArthurReis'
  - name: baseName
    type: string
    default: 'armlops'
  - name: templateML
    type: string
    default: 'provision/bicep_files/AML_provision.bicep'

variables:
  - group: Arthur_VG # Contains service_conn and subscription_id

stages:
  # This stage is a good first check, but it's redundant if your Bicep file generates unique names.
  # I've left it in as it can be useful for pre-flight checks.
  - stage: CheckResources
    displayName: 'Check Initial Resource Names Stage'
    jobs:
      - template: 1_checking_names/check-resource-names.yml
        parameters:
          # Note: These parameters are for the initial check only. The Bicep file will generate the final names.
          RESOURCE_GROUP: ${{ parameters.RESOURCE_GROUP }}
          storageAccountName: '${{ parameters.baseName }}$(Build.BuildId)' # Example of a unique name for check
          keyVaultName: '${{ parameters.baseName }}kv$(Build.BuildId)'
          appInsightsName: '${{ parameters.baseName }}ai$(Build.BuildId)'
          containerRegistryName: '${{ parameters.baseName }}acr$(Build.BuildId)'
          service_conn: '$(service_conn)'
          location: ${{ parameters.location }}

  # The Lint stage correctly checks Bicep syntax. No changes needed.
  - stage: Lint
    displayName: 'Lint Bicep Code'
    jobs:
      - job: LintBicep
        displayName: 'Lint Bicep Files'
        steps:
          - script: az bicep build --file ${{ parameters.templateML }}
            displayName: 'Lint Azure Machine Learning Bicep Template'

  # CORRECTED: This stage now passes only the 'baseName' parameter, as the Bicep file handles the rest.
  - stage: ValidateDeployment
    displayName: 'Validate Bicep Deployment'
    jobs:
      - job: ValidateBicep
        displayName: 'Validate Bicep Template'
        steps:
          - task: AzureCLI@2
            displayName: 'Validate Azure ML Template'
            inputs:
              azureSubscription: '$(service_conn)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Validating Azure Machine Learning deployment..."
                az deployment group validate \
                  --resource-group ${{ parameters.RESOURCE_GROUP }} \
                  --template-file ${{ parameters.templateML }} \
                  --parameters baseName='${{ parameters.baseName }}' \
                  --debug

  # CORRECTED: What-If also simplified to use 'baseName'.
  - stage: WhatIfOperation
    displayName: 'Run What-If Deployment'
    jobs:
      - job: WhatIfJob
        displayName: 'What-If for Azure ML Deployment'
        steps:
          - task: AzureCLI@2
            displayName: 'What-If for Azure ML Template'
            inputs:
              azureSubscription: '$(service_conn)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running What-If for Azure Machine Learning deployment..."
                az deployment group what-if \
                  --resource-group ${{ parameters.RESOURCE_GROUP }} \
                  --template-file ${{ parameters.templateML }} \
                  --parameters baseName='${{ parameters.baseName }}' \
                  --debug

  # CORRECTED: Deploy stage also simplified.
  - stage: Deploy
    displayName: 'Deploy Azure ML Resources'
    jobs:
      - job: DeployResources
        displayName: 'Deploy Azure ML Environment'
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy and Get Workspace Name'
            inputs:
              azureSubscription: '$(service_conn)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                WORKSPACE_NAME=$(az deployment group create \
                  --resource-group ${{ parameters.RESOURCE_GROUP }} \
                  --template-file ${{ parameters.templateML }} \
                  --parameters baseName='${{ parameters.baseName }}' \
                  --query properties.outputs.mlWorkspaceName.value \
                  -o tsv)
                
                # Write the name to a file in the agent's artifact staging directory
                echo $WORKSPACE_NAME > $(Pipeline.Workspace)/bicep_output/workspace_name.txt
              name: 'bicepDeployment'

          # Publish the directory containing the file as an artifact
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Workspace Name Artifact'
            inputs:
              targetPath: '$(Pipeline.Workspace)/bicep_output'
              artifact: 'bicep_outputs' # Name of the artifact

  # --- COMPLETELY REVISED SMOKE TEST ---
  # --- CORRECTED SMOKE TEST STAGE ---
  - stage: SmokeTest
    displayName: 'Smoke Test Deployed Resources'
    dependsOn: Deploy
    condition: succeeded()
    jobs:
      - job: SmokeTestJob
        displayName: 'Check Azure ML Resources'
        steps:
          # Download the artifact published by the Deploy stage
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Workspace Name Artifact'
            inputs:
              artifactName: 'bicep_outputs'
              downloadPath: '$(Pipeline.Workspace)/bicep_output'

          # This task checks if the main ML Workspace exists
          - task: AzureCLI@2
            displayName: 'Check Azure ML Workspace Exists'
            inputs:
              azureSubscription: '$(service_conn)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Read the workspace name from the downloaded file
                WORKSPACE_NAME=$(cat $(Pipeline.Workspace)/bicep_output/workspace_name.txt)

                echo "--- Starting Smoke Test ---"
                echo "Value of variable read from artifact is: '$WORKSPACE_NAME'"

                if [ -z "$WORKSPACE_NAME" ]; then
                  echo "##[error]🔥 Could not read workspace name from artifact file."
                  exit 1
                fi

                echo "Checking for Azure ML Workspace: $WORKSPACE_NAME"
                # This command will fail the step if the workspace doesn't exist
                az ml workspace show --name "$WORKSPACE_NAME" --resource-group "${{ parameters.RESOURCE_GROUP }}"
          
          # This task verifies the existence of resources linked to the workspace
          - task: AzureCLI@2
            displayName: 'Verify Associated Resources'
            inputs:
              azureSubscription: '$(service_conn)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Each task must read the file independently
                WORKSPACE_NAME=$(cat $(Pipeline.Workspace)/bicep_output/workspace_name.txt)
                
                if [ -z "$WORKSPACE_NAME" ]; then
                  echo "##[error]🔥 Could not read workspace name from artifact file."
                  exit 1
                fi

                echo "Verifying associated resources for workspace $WORKSPACE_NAME..."
                KEYVAULT_NAME=$(az ml workspace show --name "$WORKSPACE_NAME" -g "${{ parameters.RESOURCE_GROUP }}" --query 'key_vault' -o tsv | xargs basename)
                STORAGE_ACCOUNT_NAME=$(az ml workspace show --name "$WORKSPACE_NAME" -g "${{ parameters.RESOURCE_GROUP }}" --query 'storage_account' -o tsv | xargs basename)

                echo "Checking for Key Vault: $KEYVAULT_NAME"
                if az keyvault show --name "$KEYVAULT_NAME" -g "${{ parameters.RESOURCE_GROUP }}" &> /dev/null; then
                  echo "✅ SUCCESS: Key Vault '$KEYVAULT_NAME' is associated correctly."
                else
                  echo "##[error]🔥 ERROR: Key Vault '$KEYVAULT_NAME' could not be found."
                  exit 1
                fi

                echo "Checking for Storage Account: $STORAGE_ACCOUNT_NAME"
                if az storage account show --name "$STORAGE_ACCOUNT_NAME" -g "${{ parameters.RESOURCE_GROUP }}" &> /dev/null; then
                  echo "✅ SUCCESS: Storage Account '$STORAGE_ACCOUNT_NAME' is associated correctly."
                else
                  echo "##[error]🔥 ERROR: Storage Account '$STORAGE_ACCOUNT_NAME' could not be found."
                  exit 1
                fi